name: "🐛 Bug Report"
description: "Report a bug, unexpected behavior, or defect in the system"
title: "[Bug]: "
labels:
  - bug
  - triage
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Use this template to report a **bug or defect** in the system.  
        Please provide as much detail as possible to help reproduce and fix the issue.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short, clear description of the bug
      placeholder: "e.g. 'kubectl deployment fails on ARM64 builds'"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step guide to reproduce the bug
      placeholder: |
        1. Step one
        2. Step two
        3. Observe the bug
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "The deployment should succeed without errors"
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "The deployment fails with error XYZ"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Specify OS, architecture, version, CI/CD environment, etc.
      placeholder: |
        - OS: Ubuntu 22.04
        - Arch: arm64
        - Toolchain version: 1.25.5
        - CI: GitHub Actions
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How critical is this bug
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste error messages, stack traces, or screenshots
      placeholder: "Paste logs or screenshots here"

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Any extra context or links (PRs, issues, documentation)
      placeholder: "Optional"
