name: "🛠️ Task / Chore"
description: "Attività operativa, refactor, manutenzione o lavoro interno"
title: "[Task]: "
labels:
  - task
  - triage
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Usa questo template per **task tecnici**, **manutenzione**, **refactor** o **lavori operativi interni**.
        Non è destinato a **bug** o **feature request** (usa i template dedicati).

  - type: input
    id: summary
    attributes:
      label: Sommario
      description: Descrizione breve e chiara del task
      placeholder: "Refactor della pipeline di build per supportare caching multi-arch"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Contesto / Background
      description: Perché serve questo task? Fornisci contesto, motivazioni e vincoli.
      placeholder: |
        Situazione attuale:
        Perché serve questo task:
        Vincoli/assunzioni:
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Ambito del lavoro (Scope)
      description: Cosa deve essere fatto? Elenca attività e deliverable in modo esplicito.
      placeholder: |
        - Aggiornare script di setup
        - Adeguare configurazione CI
        - Rimuovere logica deprecata
        - Aggiornare documentazione CLI
    validations:
      required: true

  - type: dropdown
    id: task_type
    attributes:
      label: Tipo di task
      description: Seleziona la categoria che meglio descrive il task
      options:
        - Refactor
        - Manutenzione
        - CI/CD
        - Infrastruttura
        - Aggiornamento dipendenze
        - Hardening sicurezza
        - Altro
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priorità
      options:
        - Bassa
        - Media
        - Alta
        - Critica
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Criteri di accettazione
      description: Definisci quando il task può considerarsi completato
      placeholder: |
        - [ ] Il setup locale completa senza errori (Windows/Linux/macOS)
        - [ ] CI verde (lint, type-check, test)
        - [ ] Documentazione aggiornata (README/CONTRIBUTING)
        - [ ] Nessun segreto nei log
    validations:
      required: true

  - type: checkboxes
    id: impact
    attributes:
      label: Valutazione impatto
      description: Seleziona tutte le voci applicabili
      options:
        - label: Nessun impatto lato utente
        - label: Cambiamento di comportamento interno
        - label: Impatto su CI / tooling
        - label: Potenziale breaking change
        - label: Modifica correlata alla sicurezza

  - type: textarea
    id: risks
    attributes:
      label: Rischi / Mitigazioni
      description: Eventuali rischi noti e azioni di mitigazione
      placeholder: |
        - Rischio: ...
        - Mitigazione: ...
        - Rollback plan: ...
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: Dipendenze
      description: PR/issue/moduli da cui dipende questo task (se presenti)
      placeholder: |
        - Dipende da: #123, #456
        - Blocca: #789
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Note aggiuntive
      description: Contesto extra, link, diagrammi, riferimenti
      placeholder: "Link a documentazione, PR correlate, diagrammi, follow-up"
